# Values formatted like "_env:ENV_VAR_NAME:default_value" can be overridden by
# the specified environment variable.

static-dir:     "_env:STATIC_DIR:static"
host:           "_env:HOST:*4" # any IPv4 host
port:           "_env:PORT:3000"
approot:        "_env:APPROOT:http://localhost:3000"
ip-from-header: "_env:IP_FROM_HEADER:false"

# Optional values with the following production defaults.
# In development, they default to the inverse.
#
# development: false
# detailed-logging: false
# should-log-all: false
# reload-templates: false
# mutable-static: false
# skip-combining: false

database:
    user:     "ouep"
    password: "ouep"
    host:     "localhost"
    port:     5432
    database: "ouep"
    poolsize: 10

copyright: Une page de Ouep.eu, par
webmaster-name: Frédéric Bisson
webmaster-mail: zigazou@free.fr

